[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "f791096232cbd44034f3c477d8f6a6b430ffafc3"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "ddf8d8c66c72bd21e19fc33a9b41d9aa2299972e27c21039c40dd28439d81b31"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "1b65c66492bb5be6d612f9fc937c8b893dbd405a"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "77e125302ebe3d6b157b60292cf29f9a9c33d8c270d1c6f95639c60754b12023"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5fd1145c508437037b366f68db6b3d58d2c462ec"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "f68776be3c2f3c32d0da3ddc0dcaa2096bf6134645766b02a0b585b73a36e2bc"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2a68235efc41b322e3d725350358c0ae8360e1c"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "712521d999c89ebd07946264784c98aa4409093ce3221c40b60499f0e44fa1c5"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "6d7b4b51387c7f0bfd3360c49c184a658e5670db"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "cd17ac11d7ba22f245afa8665397ef72b50fdf60d7f921ff35a0a6cdea7be963"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "e2334651ffd5dbe940c48507eb9291d33876e36b"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "56c4358cee646f45924a58fc06383b160ec19a874007a182ff393d20b8fe2e12"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-musl.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "66dc022eb83c4561505cd051f8a17abbe8b6ac3d"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "2d451ec884e5a203c5715bbd5ab5c958f429f72093765a19d7eb795466ed0a2a"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-w64-mingw32.tar.gz"
[[GRAMPC]]
arch = "powerpc64le"
git-tree-sha1 = "93aa105d69c6f8a0e246a3641e28f9dade1f42ec"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "3d544d8d7095aa9b9c4c8b901450bc7b381a85021a9640e1e5c7de4328b59ae8"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "ed845010024089f33b014ef88ac4b310c73d8fe7"
os = "macos"

    [[GRAMPC.download]]
    sha256 = "690b8ee83a94b208f271086b301b2aa81291b6159eb2bdd1f6e826c5cf7fce58"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-apple-darwin.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "358c8993d3e9a9a564ad0739d3bd05800fd62094"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "661686329877fc39380d0f18cd8b6c6d2f1f1e61c824730315fc809a9682568d"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "a29680d1adda52f7c2ef5deb0df0264aff2033aa"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "5c6c03e27c5f9168a5ed9239b9c4a8146563b4a709e2852c8ea11e33664b8b46"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "6998f35a2c914903f4e53964b9501894e3c59cc3"
os = "freebsd"

    [[GRAMPC.download]]
    sha256 = "9fdb9116dad77b42ad8e2e790ae31553fb31ae8cfdb7d875246508d9eb6f319a"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "f245d503080a771b65bde1c567ad8c4cf5d0dcc1"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "2006bb132351feccdbaef7c2a0d3b638e023b92f619d68b24c6b45c7211b932e"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-w64-mingw32.tar.gz"
