[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "83ee736d4e3844b872665d0844c9c35d42b79a39"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "f01fab66048de47be61aaefbb492d0e5d0d94d87394905558bd65d046ce183c3"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "dfdaf43a924961577af877d5870133ae357b8b81"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "0286e9253038e0d422e98637d354b982b53c41a9f7031f6b753254913cfef2f9"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b104bb242b8af7cbc86d405ed3374dca195f1a7"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "fe6e7b4a77581dc530ce0df4b03233e1c7c9e57107f7b39c45d810ce6194326e"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f39b7b75f54a65a7981d14329bcf8a4c05ec93c"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "bb92139ad61ad8e533129a26e932c6380422636dc490a05752e709e962086fd7"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "23ba997ee8dbfec287ded6688cc8d88f67202e10"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "890a557637fe42343194e62cdaf3773b3b6190fb48bb954768a10e68339e313c"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "292552e9c9dbc24503522bbb6c4484a096672bfb"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "9c7c113b1fcb5eb3d8f4f0f20b7278c72726a0d11025f6f9f4ffc04c50eedb38"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-musl.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "9a499077174ec7dd065eddfc9d9d9d034f634bd9"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "da4077a333f2ea0b29e49700aee25579087a9b9d9273752480652484ec6ad321"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-w64-mingw32.tar.gz"
[[GRAMPC]]
arch = "powerpc64le"
git-tree-sha1 = "1201d2a182f4f967608928e704011dd8ce7fd4d8"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "50359af6acc5218a1dd9e06ff9b06ecd83d8b0696f91d2e490db46ff7b318df1"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "7ba126abd71c6a2ea48a6601aa2b8c4ad9828232"
os = "macos"

    [[GRAMPC.download]]
    sha256 = "20f6c42b9a55127f63fb82a8d3d72d6f1179ce84d9f7d1643a0db50444cf0d81"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-apple-darwin.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "006ed855446ef2b40f17362432d1e6116576d7f9"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "c85affa9fbfd6d4bf4e6373ffdce5c74fbb081915879c16d13b7d285fbd96cdc"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "25d73c60c9b65f969966eb395147208a52093e07"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "cfa4b5eb5483cec15e5da95cc99f1f4458788a34a19313dd5747a599b1a9af36"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "fa581ef08e970e099e0187e1693b9182744c8b8e"
os = "freebsd"

    [[GRAMPC.download]]
    sha256 = "053c5d902f9dbf7e112cbd766b554b2efd1df5fce89131f51a22da82b72ef62e"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "4590bdf061bb274e5d2cfa5aa7a954221767930e"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "8dae57291372ee9d5af22b6ac8f61626f8842510b40ff7dd2e73abd2e0f5832c"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-w64-mingw32.tar.gz"
