[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "d1aab7d478e3dad016efd0c4f2d5ef7a95d8d1d9"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "a1cfeda432636b4fa5c3d54cef73bdeaf0402d1b0b88aafcb0f17b80bd7f64d1"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-musl.tar.gz"
[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "13d52013067fd9e9e0e29eacdc56721c32c0ba83"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "af9b1e2ceb96e1cc263465e3b20b73744a2698f71cef25ad55c2b8b3d68a64cb"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "d1f4aacf6378f986c8f32d8bd8524dc1e4da67ba"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "e191477bcb0194c6949f16739a37f2e3d2b20975e2752a8bc169251081a36bd8"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "757bd0af0564fc0c278a28a6e7af65c915e50152"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "990c99ca89cef30099947db864a3b4a4f6fd9f627e5e965957f33253df8b8a3b"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38ff1a92cc66b073ab27dff0d9b4e84e92501002"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "e1af3cd065419487474738c799c5705d56d362dad7b29763f475c49593be0459"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "8bf7ae6aa619c1a76ed86345814b3fbb8f943075"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "8f9cfdfc8155d000e3f3af7fa3e266d3751491dfccc86c1663088eb1f9632372"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "9e768b10f7f1e2e1e737511a636695781b48a54a"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "361984ec9e628210e740944c4c6723bf56933595e003065e023f1d5d8acec7fd"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-w64-mingw32.tar.gz"
[[GRAMPC]]
arch = "powerpc64le"
git-tree-sha1 = "8a0f6595dba97b71aa062c7345197f8f4be7da60"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "6d52baa5e04ec848200f870ae3a306ead3de64ba06c5a10c9a8a78ab196ff7e9"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "c497057733f6bda49da982d8152933093611150a"
os = "macos"

    [[GRAMPC.download]]
    sha256 = "ffb6e2c9188f8677db546972ce6ba559f4618ccde7227bd9b71b8d9c5d92033a"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-apple-darwin.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "7a164959646fc02fbddd6a534478abddb5874bd6"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "416b9d977da09230f5db1af88eecf969ebc7aa0001c17b7f9e76b749e91b8855"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "52305cae533e83c0deb7fff679560a4de2af7b01"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "c8e627dc4963193b6d5778c17b0d323e08fb03d2cb8e49a961b7766ee473a414"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "e900817b7e52466fc1c05ea5be0102d7659af508"
os = "freebsd"

    [[GRAMPC.download]]
    sha256 = "f5324a7f2f8c1af98fe8bd598f6ca552ef89251cdd69a5486ba83b0e2a007022"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "3301e96fdb9f71cc925f73c615ec85ac12643f72"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "ed8ded12f7a80632d1355568dc10cdc53f81026768ea34d765ead9dfdf475e58"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-w64-mingw32.tar.gz"
