[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "2d8daee0c240076ae0346848181ea91a2e4da3b1"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "caa74f84e8547d99e487de1719f79cd17150ffea785f0857c9eb01bc3b829595"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "de1c5ab902407dbae15fa0db96ebd08dc3fa8395"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "b63e33edd679a9f7ea75a08d1f283565dbdc6578444689c36764831c72606683"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04083a4f2604ee031b7c13c22b41b0835da8c797"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "b4cc3f93e59988451dc62571549b2a6899383f125bcb3b8b8b757f9a399948e7"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "506ea7db441aa224fd645f2cdff2b3b0dacc4cd0"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "af381aef670dd1fb7d4727590e760d364ed7c9fe54f3af6c6e1b4e6697a022c5"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "3f90504c32d814b94ce5b32a3d77c1f2d676432e"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "05f0553951a429b4a1e885fb98aadc5bbeacaad907983a6f27b7688ae58a4c65"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "d1aab7d478e3dad016efd0c4f2d5ef7a95d8d1d9"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "a1cfeda432636b4fa5c3d54cef73bdeaf0402d1b0b88aafcb0f17b80bd7f64d1"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-musl.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "5bc85840d3fed97dfac54a9a624dfcd2e97334e6"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "56498a449cd4501064fa4475f0d867463baa78210a4f47e87c5be4fa5201e01a"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-w64-mingw32.tar.gz"
[[GRAMPC]]
arch = "powerpc64le"
git-tree-sha1 = "80f706147d368d4ecf20e83e5f30600364be44c7"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "c441f26c831e3965de0aef7fc34df3f743dc153391fa8df357cb4f0976d12676"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "2af7cbfa39b94279b1b388a15166bfbe8dca9ac0"
os = "macos"

    [[GRAMPC.download]]
    sha256 = "4d3479d041322d0572cf6854b08a3c06c7701a191139ac353f54ab10de7c95bb"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-apple-darwin.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "2325f7e2969582737aaf9218a168f21e469497a1"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "ae3833725191101a8cc2671b0b6838ca3a073197977e8e72428960243a43e23b"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "fd73ceb2c319a51dfac0e3b28263d936cd4e89fd"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "09c63af52fd5d7b324d887d6735c4201e257c888bbd395bd0f4697a86062ab4f"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "5867fe70c97e2a4e64cf88cc991c0abc4ea5df9b"
os = "freebsd"

    [[GRAMPC.download]]
    sha256 = "852e8a861a21c39f2b74bf12c0c4c048611fe738138bc6512506ad7b4baabfbc"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "f7959aa39a186dd019a4afef333dc7e33d0eedb2"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "fff8d7326a5a91002ad2f291199bde8cf73c751f99e18e0738d6ebec2d516e1b"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-w64-mingw32.tar.gz"
