[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "4b3d8869cedb3574dd6af5304b2db6010f1abc6f"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "9827df765b40d1257c2f71e6edd07ba1c4d6faeb46ffaa2f0c91a6ef4099736a"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "aarch64"
git-tree-sha1 = "9cb2b2ce37924b44e0599a59c44330339ecc677d"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "70c33d578e9928a5e4dfec7f4e7a3f5c109d59fc7f56b8905ee900456199061a"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.aarch64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "669081bd08c84377643a310a6a841fd4a13ffab7"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "e24b7f36eed587ae3111d943296171afb9c0fd5abe8b59cc9ed849b45fd7a80c"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[GRAMPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6b3411861053bc6935ae521c1563821c151cf6f2"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "50fd040bb57567463a679f0da343928859d4f7be5e713975a76d9d018b33eef6"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "111ce215452203630837cf69ab5d764b1029789a"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "095ef5b279c8ac70d6cbcc438c0034de0cbcd46cb69c923c9afc3dae3ed84f16"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "bfdcfb0371d67b5af76feaf7218d8b46e28aa6d9"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "2374667130ed772eeb0ac30816dbba2277d92079a02a6036ac401f0d0ce8cac7"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-linux-musl.tar.gz"
[[GRAMPC]]
arch = "i686"
git-tree-sha1 = "f93f97f58b05cd4b9af7d626c2a07bd99f7aa82a"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "59bf589600e5ddbb2e2abf80ed694c3ead0a25d58d07e921294bbca422605e3b"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.i686-w64-mingw32.tar.gz"
[[GRAMPC]]
arch = "powerpc64le"
git-tree-sha1 = "86851c694c1b33689bc68118bdd41eebe894113d"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "a73225f4d46bfa83cffe45660a4df3d144c9c979ac61807046fd2538f6cce8a1"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "f82bd04980abc0b85147fb65eb419ef9123a00c7"
os = "macos"

    [[GRAMPC.download]]
    sha256 = "fc48f37ef430acc5cdd36d17aa84e7045e4a5c784c8645ad3005fe46d608308b"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-apple-darwin.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "38cc614a7169d93df58828a5b76d73b87e0bf737"
libc = "glibc"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "2f185ed33f68a4fc59e0fa0755c6a4690e97c7b3272b6aac7cfbe35a69f8fc1f"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-gnu.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "78b049caeb22b6b89e93d4c8ef558aa417b3ee8d"
libc = "musl"
os = "linux"

    [[GRAMPC.download]]
    sha256 = "2a78596df4ea889989e5a2d319303d6f8ef3d7839056b4126006382cd3d137d5"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-linux-musl.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "1d29bd30aedeb611dfb2d6a1576f9b03a42122bf"
os = "freebsd"

    [[GRAMPC.download]]
    sha256 = "1f1322542f018bbf6104d79d450db83136ebb81e58b42d6068ea187f873b96be"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[GRAMPC]]
arch = "x86_64"
git-tree-sha1 = "b3958a2d4de57da58f12f813529380a9b70c3535"
os = "windows"

    [[GRAMPC.download]]
    sha256 = "24064774749c04f96554112e344fc98b3077550e6b58ecac0a577ffd03ce55fa"
    url = "https://github.com/imciner2/grampc_jll.jl/releases/download/GRAMPC-v2.2.0+0/GRAMPC.v2.2.0.x86_64-w64-mingw32.tar.gz"
